#! bash

_gemopencomplete() {
    local cmd=${COMP_WORDS[0]}
    local subcmd=${COMP_WORDS[1]}
    local cur=${COMP_WORDS[COMP_CWORD]}

    case "$subcmd" in
        open | browse | uninstall )
            words=`echo 'puts Dir["{#{Gem::Specification.dirs.join(",")}}/*.gemspec"].collect {|s| File.basename(s, ".gemspec").gsub(/-[^-]+$/, "") }' | ruby`
            ;;
        *)
             words="browse build cert check cleanup clone contents ctags dependency edit environment fetch generate_index help install list lock migrate open outdated owner pristine push query rdoc regenerate_binstubs search server sources specification stale tumble uninstall unpack update webhook which yank";
            ;;
    esac

    COMPREPLY=($(compgen -W "$words" -- $cur))
    return 0
}

complete -o default -F _gemopencomplete gem